language: python
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -U pip setuptools
  - pip install -U pytest-runner pytest-aiohttp pytest-pep8 pytest-mock pytest-cov
  - pip install -U aiohttp_jinja2
  - pip install codecov
  - python setup.py install
script: py.test

after_success:
  - codecov
