language: python
sudo: false
python:
  - 3.4
  - 3.5
install:
  - pip install -U pip setuptools
  - pip install pyyaml
  - pip install pytest-aiohttp pytest-pep8 pytest-mock pytest-cov
script: py.test
