language: python
sudo: false
python:
  - 3.4
  - 3.5
install:
  - pip install -U pip setuptools
  - pip install pytest-runner pytest-aiohttp pytest-pep8 pytest-mock pytest-cov
  - python setup.py install
script: py.test
