swagger: '2.0'

basePath: /

info:
  title: API
  description: API
  version: 1.0.0

paths:
  /doc/{doc_id:\d+}:
    post:
      tags: [documents]
      operationId: setDocument
      description: Set document
      parameters:
        - name: doc_id
          in: path
          type: integer
          minimum: 0
        - name: body
          in: body
          schema:
            type: object
            additionalProperties: false
            properties:
              a:
                type: integer
                minimum: 0
      responses:
        200:
          description: OK
        400:
          description: validation error
