swagger: '2.0'

basePath: /api

info:
  title: API
  description: API
  version: 1.0.0

paths:
  /doc/{doc_id:\d+}:
    post:
      tags: [documents]
      operationId: setDocument
      description: Set document
      parameters:
        - name: doc_id
          in: path
          type: integer
          minimum: 0
        - name: body
          in: body
          schema:
            $ref: 'swagger.yaml#/definitions/Document'
      responses:
        200:
          description: OK
        400:
          description: validation error

definitions:
  Document:
    type: object
    additionalProperties: false
    properties:
      doc_id:
        type: string
      text:
        type: string
    required:
      - text
